# Generated by Django 5.2.5 on 2025-08-16 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arches_saved_search', '0003_savedsearch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InclusionRule',
            fields=[
                ('inclusionruleid', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('modulename', models.TextField(blank=True, null=True)),
                ('classname', models.TextField(blank=True, null=True)),
                ('definition', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inclusion_rules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuerySetRule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('arches_rbac_permissions.inclusionrule',),
        ),
        migrations.CreateModel(
            name='SearchRule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('arches_rbac_permissions.inclusionrule',),
        ),
    ]
