# Generated by Django 5.2.5 on 2025-08-13 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arches_rbac_permissions', '0001_initial'),
        ('models', '12009_language_single_default_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationLink',
            fields=[
                ('registrationlinkid', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('used', models.DateTimeField(null=True)),
                ('metadata', models.JSONField(blank=True, db_column='metadata', null=True)),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='models.resourceinstance')),
            ],
            options={
                'db_table': 'registration_links',
                'managed': True,
            },
        ),
    ]
