# Generated by Django 5.2.5 on 2025-08-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arches_inclusion_rule', '0004_inclusionrule_querysetrule_searchrule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuerySetRule',
        ),
        migrations.DeleteModel(
            name='SearchRule',
        ),
    ]
