# Generated by Django 4.2.4 on 2023-11-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    forward = """
        """
    
    reverse = """
        """

    operations = [
            #migrations.CreateModel(
            #    name='SystemRecord',
            #    fields=[
            #        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            #        ('state_details', models.JSONField(blank=True, null=True)),
            #        ('state_time', models.DateTimeField(auto_now_add=True)),
            #    ],
            #    options={
            #        'db_table': 'system_record',
            #        'managed': True,
            #    },
            #),
            #migrations.RunSQL(forward, reverse),
    ]
